image: maven:3.8.6-openjdk-11
variables:
    MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

stages:
    - build
    - package
    - deploy


build:
    stage: build
    only:
        - develop
    except:
        - tags
    script:
        - echo 'Build project'
        - 'mvn --settings $MAVEN_SETTINGS compile'
    cache:
        paths:
            - ./target
            - ./.m2

package:
    stage: package
    only:
        - develop
    except:
        - tags
    script:
        - 'mvn --settings $MAVEN_SETTINGS package -Dmaven.test.skip=true'
    artifacts:
        paths:
            - target/*.jar
    cache:
        policy: pull
        paths:
            - ./target
            - ./.m2

deploy:
    image: docker:latest
    stage: deploy
    only:
        - develop
    except:
        - tags
    script:
        - ls -l
        - docker build -t auth-service:latest .
        - docker tag auth-service:latest 158.160.6.130/auth-service:latest
        - docker push 158.160.6.130/auth-service:latest
