image: maven:3.8.6-openjdk-11

services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

stages:
    - build
    - package
    - deploy


build:
    stage: build
    only:
        - develop
    except:
        - tags
    script:
        - echo 'Build project'
        - 'mvn -Dmaven.repo.local=./.m2/repository compile'
    cache:
        paths:
            - ./target
            - ./.m2

package:
    stage: package
    only:
        - develop
    except:
        - tags
    script:
        - 'mvn package -Dmaven.test.skip=true'
    artifacts:
        paths:
            - target/*.jar
    cache:
        policy: pull
        paths:
            - ./target
            - ./.m2

deploy:
    image: docker:latest
    stage: deploy
    only:
        - develop
    except:
        - tags
    script:
        - docker login 158.160.6.130:5000 -p deployer -u deployer
        - docker build --no-cache -t auth-service:latest .
        - docker tag auth-service:latest 158.160.6.130:5000/auth-service:latest
        - docker push 158.160.6.130:5000/auth-service:latest
