image: maven:3.8.6-openjdk-11

services:
    - name: docker:dind
      alias: dockerdaemon
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
    DOCKER_HOST: tcp://dockerdaemon:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    SERVER_IP: "158.160.6.130"

stages:
    - build
    - package
    - build and push image
    - deploy


build:
    stage: build
    only:
        - develop
    except:
        - tags
    script:
        - echo 'Build project'
        - 'mvn -Dmaven.repo.local=./.m2/repository compile'
    cache:
        paths:
            - ./target
            - ./.m2

package:
    stage: package
    only:
        - develop
    except:
        - tags
    script:
        - 'mvn package -Dmaven.test.skip=true'
    artifacts:
        paths:
            - target/*.jar
    cache:
        policy: pull
        paths:
            - ./target
            - ./.m2

build_and_push_image:
    image: docker:latest
    stage: build and push image
    only:
        - develop
    except:
        - tags
    before_script:
        - docker login -u "$DOCKER_LOGIN" -p "@DOCKER_PASS" docker.io
    script:
        - docker build --no-cache -t $DOCKER_LOGIN/auth-service:latest .
        - docker push $DOCKER_LOGIN/auth-service:latest


deploy:
    image: ubuntu:latest
    stage: deploy
    only:
        - develop
    except:
        - tags
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    script:
        - ssh kechin@SERVER_IP "docker ps -a"
