image: maven:latest

variables:
    MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

stages:
    - notify

notify-job:
    stage: notify
    script:
        - echo "Я работаю"
        - pwd
        - docker ps -a