image: docker:latest

variables:
    DOCKER_DRIVER: overlay

stages:
    - build
    - deploy


build:
    image: maven:3.8.6-openjdk-11
    stage: build
    only:
        - develop
    except:
        - tags
    script:
        - echo 'Clean project'
        - "mvn clean install"
    artifacts:
        paths:
            - target/*.jar

deploy:
    stage: deploy
    only:
        - develop
    except:
        - tags
    script:
        - ls -l
        - docker build -t auth-service:latest .
        - docker tag auth-service:latest 158.160.6.130/auth-service:latest
        - docker push 158.160.6.130/auth-service:latest
