spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: ${SERVER_PORT}
springdoc:
  swagger-ui:
    path: /docs/

jwt:
  secret-code: ${SECRET_KEY}
  life-time: ${LIFE_TIME}